### ISSUE TITLE
Migrate to a Build System

### ISSUE THREAD

**Issue by stuartmscott** [AletheiaWareLLC/PerspectiveSuite#4]
Currently PerspectiveSuite is built by executing build.sh which invokes the submodule's build.sh. This solution has been simple and easy to maintain, however as the project develops it should migrate to a build system. At this point it is still unknown which of the available build systems (Ant, Bazel, Gradle, Make, Ninja, Tup, et al.) would be most suitable.

From https://github.com/AletheiaWareLLC/PerspectiveSuite/pull/3#issuecomment-534659545

> Actually, using build.sh isn't a great option, IMHO, a "real" make system should be used in the future.

>A related issue with the current build system is that every project is unconditionally "built" every time. What I ended up doing for llvm in the pony llvm Makefile was creating "LLVM_TGT_DIR" variable and using it in llvm-base.rules to quickly skip steps that had completed. It's not perfect but under normal circumstances llvm only needs to be created once and wasting time runing "make" with nothing to do was aggravting as doing nothing on llvm still takes time and casued too much output.

>PerspectiveSuite has a similar issue as typically only a small subset of the submodules are being worked on at any one time, i.e. I'm guessing it's mostly PerspectiveAndroid.

**Comment by winksaville** [comment]
Closed with #9 and #5
